"""Inicial

Revision ID: 84396322ccdc
Revises: 
Create Date: 2022-10-26 00:52:56.673576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84396322ccdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
